services:
  geth-for-codex:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - 8545:8545
    environment:
      - GETH_ARGS=--http --http.addr 0.0.0.0
      - IS_BOOTSTRAP=1
  geth-for-codex2:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - 8546:8546
    environment:
      - GETH_ARGS=--http --http.addr 0.0.0.0
      - NUMBER_OF_ACCOUNTS=3
      # - IS_BOOTSTRAP=1