services:
  geth-for-codex:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - 8545:8545
    environment:
      - GETH_ARGS=--http --http.addr 0.0.0.0
      - ENABLE_MINER=1
      - UNLOCK_START_INDEX=0
      - UNLOCK_NUMBER=1
